name: Resizable
author: rpflo
category: Interface
tags: [drag, resize]
docs: http://moodocs.net/rpflo/mootools-rpflo/Resizable
demo: http://mooshell.net/rpflo/ry8vm/embedded/result,js,css,html/
current: 0.1